#!/bin/bash
#
# Pulls /youthfit/prod/* parameters from SSM and writes /etc/youthfit/.env.
# Run by user-data at first boot, and by youthfit.service before docker compose.
#
# Requires AWS credentials from EC2 instance profile (youthfit-ec2-profile).

set -euo pipefail

ENV_FILE="/etc/youthfit/.env"
TMP_FILE="$(mktemp)"
REGION="ap-northeast-2"

# 환경변수 키 매핑: SSM path → env var name
declare -A MAPPING=(
  ["/youthfit/prod/db/host"]="DB_HOST"
  ["/youthfit/prod/db/name"]="DB_NAME"
  ["/youthfit/prod/db/username"]="DB_USERNAME"
  ["/youthfit/prod/db/password"]="DB_PASSWORD"
  ["/youthfit/prod/jwt/secret"]="JWT_SECRET"
  ["/youthfit/prod/openai/api-key"]="OPENAI_API_KEY"
  ["/youthfit/prod/kakao/client-id"]="KAKAO_CLIENT_ID"
  ["/youthfit/prod/kakao/client-secret"]="KAKAO_CLIENT_SECRET"
  ["/youthfit/prod/internal/api-key"]="INTERNAL_API_KEY"
)

echo "# Generated by fetch-secrets.sh at $(date -Iseconds)" > "$TMP_FILE"
echo "# DO NOT EDIT MANUALLY. Source of truth: SSM Parameter Store /youthfit/prod/*" >> "$TMP_FILE"
echo "" >> "$TMP_FILE"

for path in "${!MAPPING[@]}"; do
  var_name="${MAPPING[$path]}"
  value=$(aws ssm get-parameter \
    --name "$path" \
    --with-decryption \
    --region "$REGION" \
    --query 'Parameter.Value' \
    --output text)

  if [ -z "$value" ] || [ "$value" = "PLACEHOLDER_REPLACE_VIA_CLI" ]; then
    echo "ERROR: $path is empty or placeholder. Aborting." >&2
    rm -f "$TMP_FILE"
    exit 1
  fi

  echo "${var_name}=${value}" >> "$TMP_FILE"
done

# Static config (non-secret)
{
  echo ""
  echo "# Static config"
  echo "ECR_BACKEND_URL=$(aws ssm get-parameter --name /youthfit/prod/_meta/ecr-backend-url --region $REGION --query 'Parameter.Value' --output text 2>/dev/null || echo '')"
  echo "IMAGE_TAG=latest"
  echo "SPRING_PROFILES_ACTIVE=prod"
  echo "TZ=Asia/Seoul"
} >> "$TMP_FILE"

install -m 600 -o root -g root "$TMP_FILE" "$ENV_FILE"
rm -f "$TMP_FILE"

echo "Wrote $ENV_FILE ($(wc -l < $ENV_FILE) lines)"
